# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Museum of Modern Email
headline: <span>Museum</span> <small>of</small> <span>Modern</span> <span>Email</span>
email: kirk.bentley@wordfly.com
description: "The Museum of Modern Email is dedicated to advancing the email arts. We feature beautiful and thoughtfully designed email campaigns created by performing arts and culture organizations from around the world."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://museumofmodernemail.com" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: emailmuseum
instagram_username: emailmuseum
twitter_username: emailmuseum

# Build settings
markdown: kramdown
plugins:
  - jekyll-babel

defaults:
  -
    scope:
      path: ""
      type: "emails"
    values:
      layout: "email"

collections:
  emails:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
