title: Museum of Modern Email
headline: <span>Museum</span> <small>of</small> <span>Modern</span> <span>Email</span>
email: kirk.bentley@wordfly.com
description: "The Museum of Modern Email is dedicated to advancing the email arts. We feature beautiful and thoughtfully designed email campaigns created by performing arts and culture organizations from around the world."
baseurl: ""
url: "https://museumofmodernemail.com"
facebook_username: emailmuseum
instagram_username: emailmuseum
twitter_username: emailmuseum
markdown: kramdown
plugins:
  - jekyll-babel

defaults:
  -
    scope:
      path: ""
      type: "emails"
    values:
      layout: "email"

collections:
  emails:
    output: true
